### PR TITLE
Add some mappings that are lost when using forward-unbound-keys=none

### PR DESCRIPTION
**Pull request by Carpetsmoker**
Since they aren't passed to QWebKit, these (common) mappings do nothing any
more, which is rather surprising IMHO.

One mapping I didn't add is <Tab> to go to the next link/input ("poor man's
caret mode")... It's probably not that useful in Qutebrowser?

Not sure of there are more mappings?

### CODE REVIEW

**Comment by The-Compiler** [comment]
The problem with this is that the behaviour will be slightly different in some corner cases - that's why I pass these keys through.

I don't get the rationale behind this - what's the difference between setting `forward-unbound-keys` to `auto` and setting it to `none` and emulating the same thing?

**Comment by Carpetsmoker** [comment]
If I set it to `auto`, we're back at #955 ...

> The problem with this is that the behaviour will be slightly different in some corner cases - that's why I pass these keys through.

Okay. Perhaps this can be fixed?

**Comment by The-Compiler** [comment]
So your issue in #955 is that they do the site-specific things instead of only scrolling, correct?

I don't think there's a good solution for that - but I don't think those should be bound by default.

I even changed `hjkl` to fake cursor keypresses instead of using the scroll API because of some corner cases (with different scrollable `div`s) which can't really be handled via the QtWebKit scrolling API. This means even using those will give you the site-specific behaviour.

You can of course rebind cursor keys and `hjkl` to use the `:scroll-px`/`-perc`/`-page` commands (and that'll work even with `forward-unbound-keys` set to `auto`, but I'd rather not do that as a default, sorry.

Is it okay if I close this?

**Comment by Carpetsmoker** [comment]
Right, I see what you mean. This also explains why `<Space>` doesn't work in some pages.

What needs to be done, is for the scrolling commands to take a parameter to scroll the active scrollable element, rather than the page.

You can close it for now, maybe I'll work on it later...

**Comment by The-Compiler** [comment]
> What needs to be done, is for the scrolling commands to take a parameter to scroll the active scrollable element, rather than the page.

I don't think the QtWebKit API allows that, unfortunately.

With QtWebEngine this could be a possibility, as it should be possible to scroll via JS even when JS is disabled for the page.

I also requested a C++/Python API for scrolling with QtWebEngine in [QTBUG-48323](https://bugreports.qt.io/browse/QTBUG-48323) - I added a comment there requesting that the current element can be scrolled as well.

**Pull request closed without merging**
