### PR TITLE
Sortfilter tests

### PR DESCRIPTION
**Pull request by rcorre**

### CODE REVIEW

**Comment by rcorre** [comment]
Any idea why `filterAcceptsRow` would [get an invalid index](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/completion/models/sortfilter.py#L139)?

Its the only thing between me and 100% test coverage for this module and I have no idea how to trigger it. Maybe I should just call it dead code and get it out of there :grin:

**Comment by rcorre** [comment]
I'm not clear on what "No entries in parent model" means, but an empty category doesn't seem to do it. Maybe it's an empty column that is used for sorting? That won't happen when adding entries with `new_item` as it provides default values for `desc` and `misc`

**Comment by The-Compiler** [comment]
Hmm, this was added on purpose in 3df5e13c65550daf8680f14787d7d27ec2523fb4. I guess we never have a completely empty model?

I'm not sure if it's a good idea to remove it, but you could mark it with a `# pragma: no cover` I guess.

**Comment by The-Compiler** [comment]
Also, is it possible to write a test for the `QSortFilterProxyModel ` warnings we get in #1600? Then you could mark the test as `xfail` (see [pytest docs](http://doc.pytest.org/en/latest/skipping.html#mark-a-test-function-as-expected-to-fail)) so we at least have an automated reproducer for that.

**Comment by rcorre** [comment]
Huh, I'd think [this](https://github.com/The-Compiler/qutebrowser/blob/master/tests/unit/completion/test_completionwidget.py#L101) would repro that, if anything, but it doesn't seem to.

**Comment by The-Compiler** [comment]
It seems like tabbing (i.e. `:completion-item-next`) is needed to trigger it?

**Comment by rcorre** [comment]
Yeah, this actually happens in `selectionChanged` of the completionwidget after `completion_item_next`. `selectionChanged` _does_ get called in the test I linked above, so I have no idea why it doesn't trigger the bug.

**Comment by The-Compiler** [comment]
Okay - no clue either! Do you want to add the `# pragma: no cover` and add the file to `PERFECT_FILES`?

**Comment by rcorre** [comment]
So, locally I'm seeing `qutebrowser/browser/webkit/webkitinspector.py has 100% coverage but is not in perfect_files!`. I'm not quite sure why I would have increased coverage of `webkitinspector`, so I'm gonna wait to see if Travis agrees with that.

**Comment by The-Compiler** [comment]
You see this because some inspector tests in `misc.feature` only run when windows are actually shown on screen (i.e. on Linux without Xvfb installed, or on Windows/OS X). They're skipped otherwise because they need something focusing new windows.

I added that file to `WHITELISTED_FILES` in 126e3fd01b93525d80975d586c373ba0ed2ddadf so that shouldn't happen anymore.

FWIW, if you are on Linux, I can strongly recommend installing Xvfb to be able to run the tests without annoying windows popping up :wink:

**Comment by rcorre** [comment]
Really glad you mentioned Xvfb! I'd been setting `qute-name` on the test instance and had a special window manager rule to stick them on an unused workspace :laughing:

**Pull request merged**
