### PR TITLE
Use lists instead of tuples for comparing

### PR DESCRIPTION
**Pull request by blyxxyz**
Per one of the diff comments on #1597:
> I used to use a tuple for constant things, but nowadays I'd actually prefer a list as a tuple is something more heterogeneous (i.e. it makes sense to have a `(x, y)` point as a tuple, but a list of points would be a list).

> At some point I should probably change it to a list everywhere :wink:

### CODE REVIEW

**Comment by The-Compiler** [comment]
Nice! Did you automate this somehow?

I think @Kingdread also likes to use sets (`{elem1, elem2, elem3}`, without `:`, otherwise it's a dict) for this purpose - it probably makes sense to change those occurences too.

**Comment by blyxxyz** [comment]
I automated most of it with Emacs. I used ag.el to search for occurrences of ` in (` and a macro with `forward-sexp` to fix them.

**Comment by Kingdread** [comment]
Sets - like lists - are homogenous though, and in some cases the real right thing would be to convert many of those lists to sets ... But we're getting into bikeshedding territory here :wink:

Though I agree that the tuples were not "used in the way a tuple is normally used".

**Comment by The-Compiler** [comment]
Awesome! LGTM, will merge tomorrow morning if the tests pass.

**Comment by The-Compiler** [comment]
@Kingdread I agree, and that's why I didn't complain about you using sets for this before (because it was a mess anyways). A quick straw poll in the `#python` IRC channel found out that people would use lists and found sets a bit weird to read (not "wrong", just uncommon), which is my rationale here :wink:

**Comment by The-Compiler** [comment]
Thanks! Let's hope this doesn't make too many PRs conflict...  :laughing:

**Pull request merged**
