### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by munyari**
Addresses #1379

### CODE REVIEW

**Comment by The-Compiler** [comment]
As discussed in #1379 I think this should be something more lightweight - maybe just something like this?

```
Please remember to mention your version info (qutebrowser, Qt, PyQt, OS/distribution) from the `qute:version` page or `qutebrowser --version`

---
```

will render as:

> Please remember to mention your version info (qutebrowser, Qt, PyQt, OS/distribution) from the `qute:version` page or `qutebrowser --version`
>
> ---

cc @rcorre

**Comment by munyari** [comment]
I've simplified the template. Should I squash these commits into one?

**Comment by The-Compiler** [comment]
I think it's better to keep them separate, always good to keep history.
Something I missed (sorry!) - can you move it into a `.github` folder? That'll work as well, and clutter the root directory less (especially if we add a PR template too at some point, though I'm not sure that's needed).

**Comment by munyari** [comment]
Not a problem at all :smile:

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
