### PR TITLE
Updated OS X instructions

### PR DESCRIPTION
**Pull request by priezz**
Previous instructions installed some old version. 
Native app setup added.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks for your contribution! Though I won't merge this, for these reasons:

> Previous instructions installed some old version.

That's not "some old version" - it's the latest released version, v0.1.4. I plan to release v0.2 soon, but there are [still some bugs](https://github.com/The-Compiler/qutebrowser/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.2) to be fixed before that.

I hope I'll release new versions faster after that - but using the git version might be unstable at times, as it's work-in-progress and not tested very well. So I think encouraging that in the install instructions (and even auto-pulling on each launch) is a bad idea.

> Native app setup added.

The setup instructions seem like the wrong place for this kind of thing - I plan to distribute an .app in the downloads, it's just not really a priority right now - see #384.

Though it'd be very much appreciated if you could install `cx_Freeze` and try building an `.app` via `scripts/freeze.py`!

**Comment by priezz** [comment]
Ok, I see. Version 0.1.4 does not have sessions support, so for me personally it is preferable to use unstable master branch, rather than less featured release.
As for the app, that is the simpliest way of redistribution, it does not require recompilation and even does not require any additional binaries. I assume you could create "release" branch and use the approach I offered (pulling the fresh code from GitHub). I will try cx_Freeze and report here, but I suppose it will be a bit more heavyweight, than using the OS built-in Automator's binary.
Anyway, I understand your position well and thanks for your work!

P.S. I understand, you are more Linux oriented developer, but do you occasionally know any way to remove window decorations (the bar with title close/maximize/etc buttons and the title) in OS X? I currently have to use both Arch Linux and OS X and the Qutebrowser is the only "suckless" browser, which works fine on both platforms.

**Comment by The-Compiler** [comment]
> Ok, I see. Version 0.1.4 does not have sessions support, so for me personally it is preferable to use unstable master branch, rather than less featured release.

Yeah, because of things like #523 for example - I implement stuff, wait for feedback, perfectionize it, and then release ;) But of course I get people really want sessions and history completion, so that motivates me to get v0.2 out as fast as possible. 8 open issues remaining! :)

> As for the app, that is the simpliest way of redistribution, it does not require recompilation and even does not require any additional binaries. I assume you could create "release" branch and use the approach I offered (pulling the fresh code from GitHub). I will try cx_Freeze and report here, but I suppose it will be a bit more heavyweight, than using the OS built-in Automator's binary.

I think it's just a weird workflow though - getting Python from Homebrew/ports, libraries via pip, qutebrowser from the git repo, and some files via the install instructions.

With cx_Freeze (and more frequent releases), people could either use the git repo if they want to develop or are curious/brave - and the precompiled .app otherwise.

> Anyway, I understand your position well and thanks for your great work!

Thanks for understanding! :)

> P.S. I understand, you are more Linux oriented developer, but do you occasionally know any way to remove window decorations (the bar with title close/maximize/etc buttons and the title) in OS X? I currently have to use both Arch Linux and OS X and the Qutebrowser is the only "suckless" browser, which works fine on both platforms.

Probably using something like `self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)` in `qutebrowser/mainwindow/mainwindow.py:MainWindow.__init__`.

I can't easily try that on OS X though.

**Comment by priezz** [comment]
Well, I have tried `cx_Freeze` and it just works. The output directory occupies 109M. This approach still requires wrapping the output with .app structure, but it's easy as I showed in my initial proposal.

I strongly believe that the majority of qutebrowser target audience (it's OS X part) already use Homebrew/Ports, and even prefer this way of software redistribution. Those who use AppStore would probably like to have buttons, url/search bar, etc. However, if you decide to publish the app in the AppStore or create some landing page with a possibility to try the browser quickly, `cx_freexe` is the best choice for that.

`self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)` works!

**Pull request closed without merging**
