### PR TITLE
Show default config value in completion

### LINKED ISSUE #392: Show default config value in completion

### PR DESCRIPTION
**Pull request by peterlvilim**
This resolves #392.  Tested it with several different types of values.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Checks look good :)

http://qutebrowser.org:8010/builders/pullrequests/builds/4

My battery is running out, but I'll test and merge later today, thanks!

**Comment by The-Compiler** [comment]
The *Current value* section title is a bit confusing - I think it'd make sense to change that to *Current/Default values* or so.

**Comment by peterlvilim** [comment]
Fixed

**Comment by The-Compiler** [comment]
I just noticed the value is displayed without quoting, different from the current value - see `:set network user-agent` for example - would you mind taking a look at this? :)

**Comment by peterlvilim** [comment]
Will do

**Pull request merged**
