### PR TITLE
Use jseval to test insert-text with js disabled

### PR DESCRIPTION
**Pull request by paretje**
https://github.com/The-Compiler/qutebrowser/pull/2054#issuecomment-257345920

### CODE REVIEW

**Comment by paretje** [comment]
Hmm, you can't register eventlisteners when javascript is disabled. There is an other possibility using javascript, but I'm not sure: the javascript for `insert-text`, at least with QtWebEngine, is executed async from qutebrowser, but is it executed in order? If I do:
```
insert-text test
jseval alert(document.getElementById('qute-textarea').value)
```

Will the alert be executed after the javascript of `insert-text` finished?

**Comment by paretje** [comment]
Ah, of course it will ...

**Comment by The-Compiler** [comment]
Hmm, I'm not actually sure - why do you think it will? I mean, it'd make some sense, but I'm not sure whether it's guaranteed.

**Comment by paretje** [comment]
Well, javascript has an event based single-threaded architecture, hasn't it, especially in relation to the DOM. And correct me if I'm wrong, there is just one thread per page. So, the only reason why the order would be reverted is that the first "job" didn't yet start, and the order of execution isn't FIFO, but for instance a priority queue. A priority queue doesn't make sense however, except maybe within different worlds (application > content > user?).

But, I actually did some testing first:
```
jseval for(i=0 ; i<1000000000 ; i++) { 1+1 } ; alert('hello 1')
jseval --world application alert('hello 2')
```

After a little wait, I get "hello 1", followed by "hello 2".

**Comment by The-Compiler** [comment]
Sorry for the delay, and thanks for the test and the fix!

**Comment by The-Compiler** [comment]
Hmm - it still seems to be flaky? https://travis-ci.org/The-Compiler/qutebrowser/jobs/174176526

**Comment by paretje** [comment]
The `jseval` command is executed before `insert_text` is called on the webelement, due to the fact `find_focused` is asynchronous as well. So, the order of execution is `find_focused` - `jseval` - `insert_text`. Switching `jseval` with `set` would reduce the likelihood for the test to fail, but that's not really a solution.

I don't know, but is there a way to wait for a debug message in a test? Then we could wait till `insert_text` is called on the webelement before starting `jseval`.

The combination of the async nature of webengine and the absence of javascript events to rely on seems to make this quite difficult ...

**Comment by The-Compiler** [comment]
Sure - you can simply do `And I wait for "..." in the log` in a test (in the `When` section).

**Comment by paretje** [comment]
Ah ... I'm sorry for my laziness and short-sightedness ... I'll submit a PR ;)

**Pull request merged**
