### PR TITLE
Revamp remove-finished-downloads setting

### PR DESCRIPTION
**Pull request by skinnay**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thank you! Could you also add a config migration so people's configs will adjust? You'll need to add an entry to `CHANGED_OPTIONS` in `qutebrowser/config/config.py`, and map it to a function which checks the old value and returns the new one.

**Comment by skinnay** [comment]
Okay, I see how I would change the default value of false to -1 in `CHANGED_OPTIONS`, but what about people who have set it to true? What's the appropriate way of accounting for both possibilities? `CHANGED_OPTIONS` is a dictionary, so I can't add 2 entries with the same key.

**Comment by The-Compiler** [comment]
`CHANGED_OPTIONS` takes a function - and *that function* then gets the old value and returns the new one. `_get_value_transformer` is basically a factory function which returns a `transformer` function.

The cleanest way would be to adjust `_get_value_transformer` so it takes a dictionary like `{old: new, old2: new2}` instead, i.e. probably something like this (untested):

```python
def _get_value_transformer(mapping):
    # [...]
    def transformer(val):
        try:
            return mapping[old]
        except KeyError:
            return old
    return transformer
```

You'd of course have to adjust the existing calls to `_get_value_transformers` as well.

**Comment by skinnay** [comment]
Gotcha, I'll give it a try when I get home later. Luckily there's only one other call to `_get_value_transformer` to change.

**Comment by The-Compiler** [comment]
FYI, this broke downloads with `auto_remove=True` like with `:adblock-update` because a `-1` timeout got passed to `QTimer` :wink:

I fixed that in 2fc1612bd4c3698edab80115836aa9c23bde3e42.

**Comment by skinnay** [comment]
Whoops! Didn't think that part through all the way. Thanks for noticing and fixing.

**Pull request merged**
