### PR TITLE
Add support for count for special bindings

### LINKED ISSUE #1856: Bindings with control ignore counts
For example, typing "3" and pressing Ctrl-PgUp only switches a single tab back, and doesn't clear the entered count. This is a problem for #1854.

### PR DESCRIPTION
**Pull request by Enzime**
Fixes #1856.

Note: Special keybindings currently are not supported as part of keychains.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Hmm, I'm confused - @rcorre already implemented this in #1439 but indeed it doesn't seem to work? Did this break at some point?

**Comment by rcorre** [comment]
Looks like it was reverted: 2d5ffbfd02e22

Apparently I broke something and caused #1464, then never got around to doing it properly after the revert :disappointed:

**Comment by rcorre** [comment]
I think my original commit had some more tests that may be useful here, and we should add a test for whatever I broke if one doesn't already exist

**Comment by The-Compiler** [comment]
I just reverted the revert, and it seems to work fine, probably due to the changes @lahwaacz did in #1843.

I think I'd be best to re-apply the commit by @rcorre and close this PR if that's fine for everyone :wink:

**Comment by Enzime** [comment]
Yeah, I'm fine with that :+1:

**Comment by The-Compiler** [comment]
Done!

**Pull request closed without merging**
