### PR TITLE
Default faq

### PR DESCRIPTION
**Pull request by DoITCreative**
Added question about default browser.

### CODE REVIEW

**Comment by lahwaacz** [comment]
`xdg-settings` does not work properly (see https://github.com/The-Compiler/qutebrowser/issues/22#issuecomment-224507278 and the following comment). Plus, if this is going to be added to the FAQ, it should cover all major OSes.

**Comment by The-Compiler** [comment]
@lahwaacz It seemed to work fine for @DoITCreative according to them in IRC, FWIW... But yeah, xdg-utils seems to be a mess...

**Comment by lahwaacz** [comment]
Well, generally (at least in case of Linux) given all the alternatives and outdated standards which all may or may not work depending on the distribution and/or its version, I don't see much value in describing one method that is known to have worked one day and not the other day. Certainly we can't describe everything in the FAQ, so IMO the only sensible solution is linking to external resources. I'll try to find some...

**Comment by lahwaacz** [comment]
I haven't been able to find any general enough document regarding the issue. The closest match is probably the [Default applications](https://wiki.archlinux.org/index.php/Default_applications) page on the Arch wiki, which is currently kind of a mess. I'm working on a [draft](https://wiki.archlinux.org/index.php/User:Lahwaacz/Default_applications) which should clean up most of the things and then it could be linked from qutebrowser's FAQ. Although it's written primarily for Arch, it's said that our wiki is useful for other distros as well. In any case, the specifics for some distros or other OSes can be added if needed. What do you think about this suggestion?

**Pull request closed without merging**
