### PR TITLE
log: implement JSON as logging output

### LINKED ISSUE #1501: Use json logging for end-to-end tests
Parsing the normal qutebrowser log line-by-line was useful to get started writing tests, but it comes with some problems:

- Sometimes multiline-stuff is logged, which needs some changes to how things is logged or indentation
- Things like cutting off too much information when there's an exception

Instead we should have a `--json-logging` argument which gets used for end-to-end tests, a custom `logging.Formatter` which outputs a json-line for each log message, and some code to convert that back to a normal log line for output in the test process.

### PR DESCRIPTION
**Pull request by Kingdread**
Fixes #1501

Enabled via the `--json-logging` parameter.

Opening the PR to let Travis look at it.

Todo:
* ~~Update the test in `test_quteprocess.py`~~
* ~~Tests for `LogLine.formatted_str`~~

### CODE REVIEW

**Comment by The-Compiler** [comment]
Yay! Looks quite good so far.

**Comment by Kingdread** [comment]
I've worked a bit more on it and will see what Travis has to say tomorrow, then I'll look over the code again and probably test some edge cases. Feel free to post your feedback/issues :wink:

**Comment by The-Compiler** [comment]
I think it'd make sense to find all places where we added an indentation to work around getting invalid log lines. I guess the easiest way is to check for that (indented lines in the text portion of the json) and then find out where they originate from.

Hope that was clear, kind of in a hurry right now :wink:

**Comment by Kingdread** [comment]
Tracebacks inherently have indented lines, so I hope that this heuristic works better and narrows down the search :wink:

Looks like all indented log lines were from `message._log_stack` anyway, so changing that should remove most indented lines (we could probably try and delegate that to the `exc_info` parameter of the loggers anyway, which in JSON will be the `traceback` field, but then we'd need to make sure only exceptions are passed, not strings).

**Comment by The-Compiler** [comment]
Whoops - I moved some files around today, but I hope the conflicts will be straightforward to resolve. Let me know if you need help!

What's the state for this other than that?

**Comment by Kingdread** [comment]
The conflicts actually resolved themselves, rebased onto master :wink:

The idea with `_log_stack` delegating to `exc_info` probably won't work as well as I've thought, since we'd need to generate fake exceptions as a "workaround", so it's probably okay to leave it as-is.

Other than that, if there are no more issues that you see, I think it's ready.

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
