### PR TITLE
WIP: issue 1647 support X11 geometry string

### PR DESCRIPTION
**Pull request by ganwell**
Implement issue #1647

### CODE REVIEW

**Comment by The-Compiler** [comment]
I took another look with some more sleep at this today - and now that I understand what's happening I find the tokenizing solution quite elegant, so feel free to keep that.

**Comment by The-Compiler** [comment]
@ganwell Any update on this? :wink:

**Comment by ganwell** [comment]
Going to finish it on sunday.

**Comment by ganwell** [comment]
@The-Compiler Ok. Still not finished, but the parser is implemented, nice and well tested. Can we review and merge this? I will open another pull request for the command-line and execution part. I ask this since I will make steady, but very slow progress.

CI is still running, though. Of course I will fix anything that turns up, before the review!

**Comment by ganwell** [comment]
@The-Compiler Ok some flake8 things came up my flake8 doesn't tell me about for some reason.... I'll get back to when this is fixed.

**Comment by The-Compiler** [comment]
I use various flake8 plugins - you can use `tox -e flake8` to run flake8 with all the plugins in a virtualenv locally.

**Comment by The-Compiler** [comment]
This has been dead for a while now, and someone in the qutebrowser IRC channel pointed out that Qt already handles this on X11, which means using something like `--qt-arg geometry 650x555+200+300` works fine. I didn't know!

I'm therefore closing this now, thanks for the contribution though! I also learned a bit about hypothesis by looking at it :smile:

**Comment by ganwell** [comment]
@The-Compiler Sorry, for the infinite delay. Life happens... it was fun at the sprint. :smile:

**Pull request closed without merging**
