### PR TITLE
Fix crash when hovering over an invalid URL

### PR DESCRIPTION
**Pull request by rumpelsepp**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Seems like the test you added is failing because the invalid URL doesn't actually get decoded (i.e. the `%5b` stays `%5b`):

```
____ test_set_hover_url_encoded[http://example.com%5b/-http://example.com[] ____
url_widget = <qutebrowser.mainwindow.statusbar.url.UrlText text='http://example.com%5b/'>
url_text = 'http://example.com%5b/', expected = 'http://example.com['
    @pytest.mark.parametrize('url_text, expected', [
        ('http://test.gr/%CE%B1%CE%B2%CE%B3%CE%B4.txt', 'http://test.gr/αβγδ.txt'),
        ('http://test.ru/%D0%B0%D0%B1%D0%B2%D0%B3.txt', 'http://test.ru/абвг.txt'),
        ('http://test.com/s%20p%20a%20c%20e.txt', 'http://test.com/s p a c e.txt'),
        ('http://test.com/%22quotes%22.html', 'http://test.com/%22quotes%22.html'),
        ('http://username:secret%20password@test.com', 'http://username@test.com'),
        ('http://example.com%5b/', 'http://example.com['),
    ])
    def test_set_hover_url_encoded(url_widget, url_text, expected):
        """Test text when hovering over a percent encoded link."""
        url_widget.set_hover_url(url_text, 'title', 'text')
>       assert url_widget.text() == expected
E       assert 'http://example.com%5b/' == 'http://example.com['
E         - http://example.com%5b/
E         ?                   ^^^^
E         + http://example.com[
E         ?   
```

**Comment by rumpelsepp** [comment]
Das it make sense, when I just change it to sth. like this?

```python
    @pytest.mark.parametrize('url_text, expected', [
        ('http://test.gr/%CE%B1%CE%B2%CE%B3%CE%B4.txt', 'http://test.gr/αβγδ.txt'),
        ('http://test.ru/%D0%B0%D0%B1%D0%B2%D0%B3.txt', 'http://test.ru/абвг.txt'),
        ('http://test.com/s%20p%20a%20c%20e.txt', 'http://test.com/s p a c e.txt'),
        ('http://test.com/%22quotes%22.html', 'http://test.com/%22quotes%22.html'),
        ('http://username:secret%20password@test.com', 'http://username@test.com'),
        ('http://example.com%5b/', 'http://example.com%5b'),
    ])
    def test_set_hover_url_encoded(url_widget, url_text, expected):
        """Test text when hovering over a percent encoded link."""
        url_widget.set_hover_url(url_text, 'title', 'text')
        assert url_widget.text() == expected
        assert url_widget._urltype == url.UrlType.hover
```

**Comment by The-Compiler** [comment]
Yes, though you'd need to include the trailing slash with the expected URL too.

**Comment by rumpelsepp** [comment]
Ah, yeah. Copy paste error. :)

**Comment by rumpelsepp** [comment]
updated

**Comment by The-Compiler** [comment]
LGTM, will merge once the tests pass

**Comment by The-Compiler** [comment]
Thank you!

**Pull request merged**
