### PR TITLE
Add --domain to yank to yank only the domain

### PR DESCRIPTION
**Pull request by Carpetsmoker**
... As I want to copy only the domain fairly frequently.

I also changed the message in the statusline to show the actual text being
copied, which I find helpful. But if you disagree, then just undo it (it's not
that important or anything).

### CODE REVIEW

**Comment by The-Compiler** [comment]
Looks good to me, including the message change. Maybe the port should be added too, if non-standard? (I'm not sure what `QUrl::port()` will return in that case - either `-1` or `80`/`443`).

**Comment by Carpetsmoker** [comment]
Added port :-)

**Comment by The-Compiler** [comment]
Looks good - I'll test and merge later today.

**Comment by The-Compiler** [comment]
Okay, the "tomorrow" kind of today :wink:

Thanks!

**Pull request merged**
