### PR TITLE
Add insert mode feature tests

### PR DESCRIPTION
**Pull request by phansch**
This PR adds some insert mode feature tests for input and textarea tags.

Looking for some feedback now as I'm not sure what else is possible.
I'd probably add another test for the `maxlength` attribute on input fields but then again, that should be covered by the engines testsuite already. Let me know if you have more ideas for what else to test.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! I was thinking about maybe testing multiple corner cases of editable/non-editable fields, but that's covered by [test_webelem.py](https://github.com/The-Compiler/qutebrowser/blob/master/tests/unit/browser/test_webelem.py) already.

I think what'd make sense is to test those settings in `input`:

- auto-insert-mode
- auto-leave-insert-mode
- insert-mode-on-plugins (if there's some way to easily have a minimal flash example in the repo)

Ideally we'd also have some minimal testcases for all the [corner cases in webview.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/webview.py#L240-L305) - but I'm not sure if that's doable with some reasonable effort.

Since the tests are all very similar, I guess it'd make more sense to do something like [test_hints_html.py](https://github.com/The-Compiler/qutebrowser/blob/master/tests/integration/test_hints_html.py) where the test is written in Python and parametrized by simple HTML-files?

**Comment by phansch** [comment]
Ah, I wasn't even aware of the input settings, thanks! I will have a go at removing the duplication as well as adding tests for the insert mode settings. Do you think it makes sense to add tests for interacting with the `select/option` tag, too?

**Comment by The-Compiler** [comment]
I think we need to find some middle ground between not having too much end-to-end tests (because they're rather slow and brittle), and having enough so I can check basic functionality when migrating to QtWebEngine without relying on the unit tests (as they might not be ready yet).

I'd say add one or two if it's easy enough (simulating cursor presses? I hope that works with a menu open...), but don't go overboard :wink:

**Comment by phansch** [comment]
Regarding `insert-mode-on-plugins`: It seems there's no need to have an actual .swf in the repo. Using

```html
<embed id="qute-flash" width="100" height="100" src="doesnotexist.swf" />
```
is enough already to enter the insert mode when clicking it.
However I could not find a way to click the `embed` element in the tests, as hints don't seem to work with embed tags and I have no idea how to simulate cursor presses.

Looking into adding tests for the other options now :)

**Comment by The-Compiler** [comment]
Hmm, maybe you could run something like `:jseval document.getElementById("qute-flash").click()`? (untested)

**Comment by phansch** [comment]
Ok, I changed the tests from bdd-style to non-bdd integration tests. That removed a lot of duplication. I also added tests for `auto-insert-mode` and `auto-leave-insert-mode`.

For `insert-mode-on-plugins`: I couldn't get the click to work and I'm a bit limited time-wise now, so I'd prefer to do it in an extra PR and have this one merged first.

**Comment by The-Compiler** [comment]
Sure thing! I'll review and merge it later today or this week. Thanks!

There's a [pytest-bdd feature](https://github.com/pytest-dev/pytest-bdd#scenario-outlines) to parametrize scenarios, but when I tried it didn't work like I thought it would. Definitely should give it another try though.

**Comment by The-Compiler** [comment]
Seems like the tests still fail on Windows - do you have time to investigate what's going on?

**Comment by The-Compiler** [comment]
I took a quick look at this - looks like the following tests [fail on Windows])(
https://ci.appveyor.com/project/The-Compiler/qutebrowser/build/master-2414/job/yweh3t7gyvpxpqsn)

- `test_insert_mode[textarea.html-clipboard-qutebrowser-false]`
- `test_insert_mode[input.html-clipboard-amazingqutebrowser-false]`

We had to do some Windows-specific things for [`:move-to-next-word`](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/commands.py#L1589-L1608) to work properly (see #1142 and #1145). Maybe `:move-to-prev-word` needs something similar to work properly and we just didn't catch it in the tests? @artur-shaik what do you think?

**Comment by artur-shaik** [comment]
@The-Compiler yeah, I think something like those specific things need. Can we see what exactly was  yanked?

**Comment by The-Compiler** [comment]
It seems nothing at all: `message:info:303 Nothing to yank`. I think this would be easiest if someone can test and watch it on Windows (with `--qute-delay`). Do you have a Windows machine availablle, @artur-shaik? Otherwise I'll try to take a look at this somewhen over the next few days.

**Comment by artur-shaik** [comment]
@The-Compiler no, I don't have windows now.

**Comment by The-Compiler** [comment]
Hah, the actual issue has nothing to do with caret mode - it's just that `:paste-primary` does nothing on Windows :laughing: 

I think I'll change `:paste-primary` to simply paste the clipboard on Windows, that probably makes most sense, and makes those tests pass on Windows too.

**Comment by The-Compiler** [comment]
Merged - thanks @phansch, and thanks @artur-shaik for the help!

**Pull request merged**
