### PR TITLE
prevent words from the dictionary prefixing smart hints

### LINKED ISSUE #1393: word hints: "ValueError: Got invalid match type Match.ambiguous"
Report on 42a4c1c.

@NoctuaNivalis any chance you could take a look at this? :smile:

## Report

- typing a hint, m-a-l-l letters into  "malloc" hint on news.ycombinator.com
- There was probably another hint, "mall", to cause this crash, but I am not sure (did not notice).
- "malloc" was a "smart" hint (read something from url to generate hint). Are smart hints properly uniq'd against generated word hints?
- Have used the new word-hints feature since its release and have never had an ambiguous match crash before

## Config

```ini
[hints]
border = 1px solid #ff4500
opacity = 0.9
mode = word
scatter = false
uppercase = true
```

## Log

```
14:38:36 DEBUG    commands   command:run:490 command called: hint ['all', 'tab']
14:38:36 DEBUG    commands   command:run:504 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7f5529b2da68>, False, <Group.all: 1>, <Target.tab: 2>, win_id=0)
14:38:36 DEBUG    hints      hints:_init_elements:680 hints: axis, changes, ella, gold, minutes, gory, able, freedom, peep, sawn, hours, amid, gags, gene, seed, andris, thin, warn, sulk, nick, jeer, beam, bmw, loth, serf, pm, puke, lube, lacy, discuss, lion, loll, wimp, crow, lupe, ruiz, flub, malloc, dyer, ages, grid, gunk, lire, state, kadira, fri, buff, leos, tues, craw, feud, lady, loyd, date, suzy, lr, lax, mold, else, toes, pres, googles, flag, olga, rn, lola, ohsa, killing, aces, cast, lois, sale, hips, swop, eetimes, razer, hype, help, fest, turkey, ibtimes, ponyous, hies, mugs, nous, release, wololo, scow, outs, any, slur, duds, love, gelt, olav, kurt, prut, proto, github, jive, ajax, disc, colo, writ, brig, gyms, bart, mack, yawl, basic, jogs, aloe, hutu, tass, free, andy, itch, tshtf, lien, glut, hump, murk, sick, canistr, seam, knob, apr, drones, furs, rezist, pugs, pare, mire, nigh, pour, prim, duly, joys, beet, hams, burg, elorant, sake, real, hews, ultra, fins, gray, coax, kyle, puny, swig, peck, jonbaer, whiz, comment, lace, nook, burp, nkurz, yawn, deed, feta, said, wired, anus, eula, ass, ariz, toot, wrapapi, arciini, yowl, mall
14:38:36 DEBUG    message    message:set_text:323 Follow hint in new tab...
14:38:36 DEBUG    statusbar  text:set_text:59 Setting normal text to 'Follow hint in new tab...'.
14:38:36 DEBUG    hints      hints:_connect_frame_signals:642 Connecting frame <PyQt5.QtWebKitWidgets.QWebFrame object at 0x7f5529e4fe58>
14:38:36 DEBUG    modes      modeman:enter:242 Entering mode KeyMode.hint (reason: HintManager.start)
14:38:36 DEBUG    modes      modeman:_eventFilter_keypress:197 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=36 url='https://news.ycombinator.com/'>)
14:38:36 DEBUG    modes      modeman:_eventFilter_keyrelease:217 filter: False
14:38:36 DEBUG    modes      modeman:_eventFilter_keyrelease:217 filter: True
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x4d / text: 'm'
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 No match for 'm' (added m)
14:38:37 DEBUG    hints      hints:handle_partial_key:829 Handling new keystring: 'm'
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:197 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=36 url='https://news.ycombinator.com/'>)
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x41 / text: 'a'
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 No match for 'ma' (added a)
14:38:37 DEBUG    hints      hints:handle_partial_key:829 Handling new keystring: 'ma'
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:197 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=36 url='https://news.ycombinator.com/'>)
14:38:37 DEBUG    modes      modeman:_eventFilter_keyrelease:217 filter: True
14:38:37 DEBUG    modes      modeman:_eventFilter_keyrelease:217 filter: True
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x4c / text: 'l'
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 No match for 'mal' (added l)
14:38:37 DEBUG    hints      hints:handle_partial_key:829 Handling new keystring: 'mal'
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:197 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=36 url='https://news.ycombinator.com/'>)
14:38:37 DEBUG    modes      modeman:_eventFilter_keyrelease:217 filter: True
14:38:37 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x4c / text: 'l'
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Ambiguous match for 'mall'.
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Ambiguous match for 'mall'
14:38:37 DEBUG    keyboard   basekeyparser:_debug_log:107 Scheduling execution of mall in 500ms
14:38:37 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/username/git/qutebrowser/qutebrowser/app.py", line 862, in eventFilter
    return handler(event)
  File "/home/username/git/qutebrowser/qutebrowser/app.py", line 822, in _handle_key_event
    return man.eventFilter(event)
  File "/home/username/git/qutebrowser/qutebrowser/keyinput/modeman.py", line 319, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/username/git/qutebrowser/qutebrowser/keyinput/modeman.py", line 169, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/username/git/qutebrowser/qutebrowser/keyinput/modeparsers.py", line 192, in handle
    raise ValueError("Got invalid match type {}!".format(match))
ValueError: Got invalid match type Match.ambiguous!
```

### PR DESCRIPTION
**Pull request by NoctuaNivalis**
This should fix #1393. I'd still like to write some tests for this though. As this bug should be very rare, perhaps this merge should be delayed until I did? I hope to complete these tests soon (like, within a few days).

### CODE REVIEW

**Comment by The-Compiler** [comment]
Let me know if you need help with the tests! As mentioned in IRC, I'd write an end-to-end test for this, but using Python instead of a feature-file.

The following pytest [fixtures](http://pytest.org/latest/fixture.html) will likely be helpful:

- [tmpdir](http://pytest.org/latest/tmpdir.html)
- quteproc which will give you a [`QuteProc`](https://github.com/The-Compiler/qutebrowser/blob/master/tests/integration/quteprocess.py#L121) object

You can then probably do something like this (rough draft, completely untested):

```python
def test_word_hints_issue1393(quteproc, tmpdir):
    dict_file = tmpdir / 'dict'
    dict_file.write(textwrap.dedent("""
        one
        two
        three
        four
    """)

    quteproc.set_setting('hints', 'mode', 'words')
    quteproc.set_setting('hints', 'dictionary', str(dict_file))
    quteproc.open_path('data/hints/issue1393.html')
    quteproc.send_cmd(':hint')
```

**Comment by The-Compiler** [comment]
@NoctuaNivalis what's the state of this?

**Comment by NoctuaNivalis** [comment]
Well, I could probably use some help with the tests ;-)
Things are fixed, but I've failed to verify so.

```python
quteproc.wait_for(message='hints: *', category='hints')
```

This line seems to hang forever, even though the hints do appear when I test it manually.

**Comment by The-Compiler** [comment]
Looking at [Travis CI](https://travis-ci.org/The-Compiler/qutebrowser/jobs/122744290) it seems like there's a `StopIteration` exception:

```
:set hints mode word
:set hints dictionary /tmp/pytest-of-travis/pytest-0/test_word_hints_issue13930/dict
:open http://localhost:45543/data/hints/issue1393.html
:hint

DEBUG    commands   command:run:504 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7f9d440391f8>, False, <Group.all: 1>, <Target.normal: 1>, win_id=0)
ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/app.py", line 108, in <lambda>
    target_arg=target_arg))
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/app.py", line 265, in process_pos_args
    commandrunner.run_safely_init(cmd[1:])
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/commands/runners.py", line 276, in run_safely_init
    self.run(text, count)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/commands/runners.py", line 258, in run
    result.cmd.run(self._win_id, args)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/commands/command.py", line 505, in run
    self.handler(*posargs, **kwargs)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/hints.py", line 832, in start
    self._init_elements()
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/hints.py", line 691, in _init_elements
    hints = self._hint_strings(elems)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/hints.py", line 213, in _hint_strings
    return self._word_hinter.hint(elems)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/hints.py", line 1100, in hint
    hint = self.new_hint_for(elem, used_hints, words)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/browser/hints.py", line 1080, in new_hint_for
    return next(new_no_prefixes, next(fallback_no_prefixes))
StopIteration
```

This would happen if both `new_no_prefixes` and `fallback_no_prefixes` are empty I think.

**Comment by The-Compiler** [comment]
Actually the `next(fallback_no_prefixes)` is evaluated in either case, so this'll happen if `fallback_no_prefixes` is empty no matter if `new_no_prefixes` is empty or not.

**Comment by NoctuaNivalis** [comment]
Ah, and because it's called every time, the configured dictionary is too small. This also makes clear what would happen if on runs out of words on a page, so I'll fix that, too.

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
