### PR TITLE
Handle special keystrings case-insensitively.

### LINKED ISSUE #1544: :bind is case-sensitive
```
:bind <ctrl-T> message-info this
:bind <Ctrl-T> message-info shouldn't
:bind <ctrl-t> message-info work
```

Pressing `ctrl-t` still executes the originally mapped command `open -t`, but none of the above complain about a conflict.

I guess for now we should capitalize all keys when we load or set bindings (as `<Ctrl-T>` seems to be the canonical way to spell it)?

### PR DESCRIPTION
**Pull request by rcorre**
Load all special keystrings (e.g. <ctrl-a>) into memory as lowercase,
and automatically lowercase any special keystring given to bind/unbind.
This prevents <ctrl-a> and <Ctrl-A> from being treated differently.

Resolves #1544, where `:bind <ctrl-t>` would not complain even though
`<Ctrl-T>` was bound.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Seems like [those tests are failing](https://travis-ci.org/The-Compiler/qutebrowser/jobs/135194461), could you take a look please?

**Comment by The-Compiler** [comment]
Can you also add a test for overriding an existing binding, similar to #816? (I guess that issue was opened before `-f` existed, but you get the idea).

**Comment by rcorre** [comment]
> Seems like those tests are failing, could you take a look please?

Looking now. I was on a different machine where I hadn't rebuilt whatever it was I had to rebuild to run the tests (PyQt?) so I just decided to push it up and let CI sort it out :)

**Comment by rcorre** [comment]
Slightly juggled around the function signature to get it _just_ under `flake8`'s complexity limit :)

See the second commit, I think it should be a noop change (unless we're expecting a caller to explicitly pass `None`).

**Comment by The-Compiler** [comment]
Thanks! That function signature change definitely makes things cleaner, not sure why it wasn't that way earlier.

Also let me point out all those checks are open to discussion - sometimes it makes sense to locally or even globally disable a check because things are actually more readable that way. Automated checkers aren't perfect, and finding out how to make the most out of them is a continuous adjustment :wink:

**Comment by rcorre** [comment]
agreed, but in this case it actually tricked me into doing something smart :)

**Pull request merged**
