### PR TITLE
Suppress hiding hints in rapid mode

### LINKED ISSUE #1799: (Option to) suppress hiding hints in rapid mode
Right now if I start typing one hint in rapid mode, the next completion will end up disappearing as I'm typing the current one, which throws me off if I'm trying to read in advance to see what the next one would be.

### PR DESCRIPTION
**Pull request by lahwaacz**
Fixes #1799, unless someone would prefer to make this optional.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I don't see a good way to test this automatically (at least yet), but if you could add a HTML test page with a description to `tests/manual/hints` (see the existing ones for some inspiration) that'd be great.

If you prefer me adding such a thing, let me know :wink:

LGTM otherwise, but I wonder if someone speaks up which prefers this being optional.

**Comment by mlochbaum** [comment]
I would prefer for it to be optional. My hints are dark enough that I often can't see behind them, so I tend to use the time when some of them are hidden to look at other links. It's sort of silly, but I can't think of a better way to accomplish the same functionality if hints aren't hidden.

**Comment by The-Compiler** [comment]
Hmm, I can see that. Let's add an option then, should be straightforward enough.

**Comment by lahwaacz** [comment]
I added the option and a manual test now.

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
