### PR TITLE
Fix scroll JS for xkcd.

### PR DESCRIPTION
**Pull request by Spreadyy**
Fix wrong scroll.height for xkcd. Solution according to:
http://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript

### CODE REVIEW

**Comment by Spreadyy** [comment]
#1945

**Comment by The-Compiler** [comment]
Hmm, this seems to break a test related to scrolling with zoom...

**Comment by The-Compiler** [comment]
The build still fails on Travis but passes on my machine (and on OS X on Travis)...

Running in verbose mode in https://travis-ci.org/The-Compiler/qutebrowser/builds/163614039 which should tell us which values are coming back from JS.

**Comment by The-Compiler** [comment]
On Travis, the values are off by one pixel:

```
05:42:04.986 VDEBUG   webview    webenginetab:update_pos_cb:256 {'px': {'x': 0, 'y': 2771}, 'inner': {'height': 287, 'width': 400}, 'scroll': {'height': 3059, 'width': 2720}}
```

(2771 + 287 = 3058)

Locally I get:

```
08:20:50.402 VDEBUG   webview    webenginetab:update_pos_cb:256 {'px': {'x': 0, 'y': 2862}, 'inner': {'height': 286, 'width': 400}, 'scroll': {'height': 3148, 'width': 3295}}
```

**Comment by The-Compiler** [comment]
Logging the JS values locally:

```
08:31:47.960 INFO     js         webview:javaScriptConsoleMessage:132 [:68] body.scrollHeight = 3148
08:31:47.960 INFO     js         webview:javaScriptConsoleMessage:132 [:69] body.offsetHeight = 3132
08:31:47.961 INFO     js         webview:javaScriptConsoleMessage:132 [:70] elem.scrollHeight = 3148
08:31:47.961 INFO     js         webview:javaScriptConsoleMessage:132 [:71] elem.offsetHeight = 3148
```

let's see what travis says...

**Comment by The-Compiler** [comment]
We can fix the at_bottom check and position display like this:

```diff
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 1c24881..81f5604 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -258,11 +258,18 @@ class WebEngineScroller(browsertab.AbstractScroller):
             self._pos_px = QPoint(jsret['px']['x'], jsret['px']['y'])
 
             dx = jsret['scroll']['width'] - jsret['inner']['width']
-            perc_x = 0 if dx == 0 else round(100 / dx * jsret['px']['x'])
+            if dx == 0:
+                perc_x = 0
+            else:
+                perc_x = min(100, round(100 / dx * jsret['px']['x']))
+
             dy = jsret['scroll']['height'] - jsret['inner']['height']
-            perc_y = 0 if dy == 0 else round(100 / dy * jsret['px']['y'])
+            if dy == 0:
+                perc_y = 0
+            else:
+                perc_y = min(100, round(100 / dy * jsret['px']['y']))
 
-            self._at_bottom = dy == jsret['px']['y']
+            self._at_bottom = dy >= jsret['px']['y']
             self._pos_perc = perc_x, perc_y
 
             self.perc_changed.emit(*self._pos_perc)
```

but the test fails as setting the scroll position still doesn't work on those pages.

**Comment by The-Compiler** [comment]
Thanks! In fc0b62f122e44b142db6dee133a099df391ec2fa I reverted a commit to use all values again, and fixed the remaining bits in bd831939bcb9c6424dd51c1a51811d37cf5d1564 and 323d5fc9e710cc40cef5a0ab5281238df4313722.

**Comment by Spreadyy** [comment]
Nice :)

**Pull request merged**
