### PR TITLE
Pdfjs fix (take two)

### PR DESCRIPTION
**Pull request by Kingdread**
Installing `libjs-pdf` on Travis to see if the tests work.

[Review on Reviewable](https://reviewable.io/reviews/the-compiler/qutebrowser/1294)

### CODE REVIEW

**Comment by The-Compiler** [comment]
I cherry-picked 5d1cf3611fbc5e0a9a57bfd6c9f7aff0f627f871 for now :wink:

**Comment by Kingdread** [comment]
You cherry-picked the actual fix into master, so I guess the tests are fixed.

As for the test-pdfjs-on-travis-thing, we probably need some other way to deal with this, as the package provided by Ubuntu Trusty is quite outdated and doesn't match the version we're expecting, so the rewrite rules are off and everything is broken.

I guess there are several ways to fix this, but I'm not sure if one of those is the right one. We could

- re-download pdfjs every time using `update_3rdparty` on the CI, but that costs time and probably isn't needed for most builds
- adapt pdfjs so it supports old versions, but that's a lot of trouble for (in my opinion) little gain, making the whole thing even more complex and we'd need even more tests - either by version specific rewrite rules or by more sophisticated algorithms, like actually parsing the HTML and checking every link (similar to the mhtml downloader).
- wait until Travis updates Ubuntu, hoping that by then, pdfjs won't have changed again :wink:
- [insert suggestion here]

so unless we find a better (and working) way, I'm closing this for now.

Another thing that crossed my mind is if we should have a minimum version requirement scripted into qutebrowser with a page saying "Your version of pdf.js is too old. qutebrowser needs version {min_pdfjs_version} or higher.", though we could only do this for minimum version, as otherwise we'd need to constantly update the maximum pdfjs version. Or should we just use the version information from `qute:version` if a user reports a non-working pdf.js installation?

**Comment by The-Compiler** [comment]
I'll just install pdfjs on my buildbot then. OS packages from Archlinux and Debian Jessie would both work I guess?

The version check sounds good, yeah. Maybe just check it's the same major version for the maximum one?

**Comment by Kingdread** [comment]
Yeah, they should both work, at least the Arch one. If the Debian one doesn't work, I'm going to inspect the package.

The version check could work, yeah, and then again, you should update your browser and pdfjs anyway, so there's probably no harm done :wink:

**Pull request closed without merging**
