### PR TITLE
Add host placeholder to window and tab title formats

### PR DESCRIPTION
**Pull request by djfinlay**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thank you! Looks good from a first quick look, but it might be Monday until I get around to merging it.

**Comment by The-Compiler** [comment]
pylint detected a duplicate code snippet on Windows:

```
==qutebrowser.mainwindow.tabbedbrowser:175
==qutebrowser.mainwindow.tabwidget:114
        y = widget.scroll_pos[1]
        if y <= 0:
            scroll_pos = 'top'
        elif y >= 100:
            scroll_pos = 'bot'
        else:
            scroll_pos = '{:2}%'.format(y)
 
        fields['scroll_pos'] = scroll_pos
        try: (duplicate-code)
```

But I'm not sure how that's actually related to your change. Will investigate later.

**Comment by djfinlay** [comment]
I've refactored the methods for updating the tab and window titles as they were pretty similar.

**Comment by The-Compiler** [comment]
Thanks! There also was the idea of using [jinja2](http://jinja.pocoo.org/) for those settings a while ago, so you could expose `url` and do things like `{{ url.host() }}` in the setting instead.

Would you be interested to work on that by any chance? I opened a separate issue now, #1578.

**Comment by djfinlay** [comment]
No problem. Sure, I'll take a look at it tonight.

**Pull request merged**
