### PR TITLE
Named Windows (Fix #1096)

### LINKED ISSUE #1096: Named windows
* [ui]window-title-format
  * Add {name} field
  * Possibly add {name_sep} akin to {title_sep}
  * Change the default to {perc}{title}{title_sep}qutebrowser{name_sep}{name}

* Commands
  * `:open -w -n <window-name>`: opens a new window the name `<window-name>`
  * `:set-window-name <window-name>`: set the name of the current window and updates window title
  * Any other command that could open a new window should probably get the --name option as well (`:help`, etc)

* Session
  * Save the window name into the session files

### PR DESCRIPTION
**Pull request by Ram-Z**
- [ui]window-title-format
  - [x] Add {name}  and {name_sep} field
  - [ ] Change the default to {perc}{title}{title_sep}qutebrowser{name_sep}{name}

- Commands
  * [x] `:open -w -n <window-name>`: opens a new window the name `<window-name>`
  * [ ] Fix completion
  * [x] `:set-window-name <window-name>`: set the name of the current window and updates window title

- Session
  - [x] Save the window name into the session files

---
This change is [Reviewable](https://reviewable.io/reviews/the-compiler/qutebrowser/1101)

### CODE REVIEW

**Comment by Ram-Z** [comment]
The `:open -w -n` command works but breaks the completion, i.e. urls are completed directly after the `-n` instead of after the name. Not sure where to fix this.

**Comment by The-Compiler** [comment]
@Ram-Z - what's the state of this? I can look at the completion issue later, but I'd prefer if the rest was ready first :wink:

**Comment by Ram-Z** [comment]
Sorry, didn't have much time for this in the past few weeks.

I can't really use it for matching windows with my window manager. The matching rules on the title will match when the window is created and for a split second this is the application name. See [this video](http://rmz.io/qutebrowser.mkv) at 00:00:01:00, for a single frame at 50 fps the window title is `qutebrowser`. Very rarely the window will actually open with the modified title and then it is matched by my WM rules.

I believe I set the window title the soonest I can. And I don't get why it creates the window with the application name as title, the window should be created until `show()` is called.

**Comment by The-Compiler** [comment]
Odd... Can you try with this minimal example? At least my window manager (herbstluftwm) always displays `foo` correctly here:

```python
from PyQt5.QtWidgets import QApplication, QWidget

app = QApplication([])
app.setApplicationName("appname")
w = QWidget()
w.setWindowTitle("foo")
w.show()

app.exec_()
```

**Comment by Ram-Z** [comment]
The minimal example works and sets the title from the beginning. My WM (awesome) matches the window title everytime.

**Comment by Ram-Z** [comment]
Can you actually reproduce my issue? i.e. does running qb from this branch very briefly show the application name before setting the window title?

Even with the following patch, which sets the window name as soon as possible, the WM_NAME briefly contains the application name.

```diff
diff --git a/qutebrowser/app.py b/qutebrowser/app.py
index 3b9cc55..179f52b 100644
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -80,7 +80,7 @@ def run(args):
     global qApp
     qApp = Application(args)
     qApp.setOrganizationName("qutebrowser")
-    qApp.setApplicationName("qutebrowser")
+    qApp.setApplicationName("qutebrowser_test")
     qApp.setApplicationVersion(qutebrowser.__version__)
     qApp.lastWindowClosed.connect(quitter.on_last_window_closed)
 
@@ -190,7 +190,7 @@ def _process_args(args):
     session_manager = objreg.get('session-manager')
     if not session_manager.did_load:
         log.init.debug("Initializing main window...")
-        window = mainwindow.MainWindow()
+        window = mainwindow.MainWindow(name="default")
         if not args.nowindow:
             window.show()
         qApp.setActiveWindow(window)
```

**Comment by The-Compiler** [comment]
@Ram-Z sorry for not answering your question, I must've forgotten about this... :blush: 

I don't think there is a good solution for this which will work the way you want it to (i.e. with rules in your WM) - would you be okay with closing this?

**Comment by Ram-Z** [comment]
No worries.

I've been running this branch for quite a while now and only occasionally it will match the window on startup. So rarely that it actually surprises me and I'm wondering why I can't see that window on my current tag. :P

It still feels weird to me that the window title is being set to the application name for a split second. I might have another look at this in the future but feel free to close this in the meantime.

**Comment by The-Compiler** [comment]
Closing this for now - thanks for the contribution either way, and feel free to reopen or open another PR if you get it to work! :smile:

**Pull request closed without merging**
