### PR TITLE
Removed default search engines. Closes #533.

### LINKED ISSUE #533: Unable to remove predefined searchengines
The searchengines that are defined by default are always readded after a manual edit of the `qutebrowser.conf` file. They are added right after the browser is started.
There is also no way to remove searchengines using the gui.

Another problem, that isn't really related, is that after adding a new searchengine it wont appear in the list until qute is restarted.

### PR DESCRIPTION
**Pull request by error800**

### CODE REVIEW

**Comment by The-Compiler** [comment]
Not sure what to think about this. It should be possible to remove those search engines by setting it to an empty value, though *that* seems to be broken... Whoops! :blush: 

But I'd still like to ship a minimal useful set of default search engines, especially `ddg` so something like `:open ddg QWebView::load` still works.

I suggest keeping them for now, and fixing this properly with the big config revolution at #499. Other opinions? /cc @oed 

I'll take a look at why `:set searchengines ddg ""` doesn't work later today.

**Comment by oed** [comment]
I agree, it's not that important right now. No real reason to do anyting before the switch to yaml.

**Comment by error800** [comment]
It doesnt work because {} is expected in the searchengine string. And if i set google = {}, searching for 'google sucks' tries to open http://sucks :/

**Comment by flvi0** [comment]
> But I'd still like to ship a minimal useful set of default search engines, especially `ddg` so something like `:open ddg QWebView::load` still works.
> 
> I suggest keeping them for now, and fixing this properly with the big config revolution at #499. Other opinions? /cc @oed 

Well I think that having the DEFAULT should actually be sufficient.
That :: problem when not typing an engine explicitly actually
occured to me several times already. I expected to be able to just
paste it into :open. What exactly are those :: links anyways, is
that a standard URI form for external applications? Maybe we can
parse/qualify it somehow differently to make searching for scoped C+
+ symbols work as expected?

-- 
Patric Schmitz <bzk0711@aol.com>

**Comment by error800** [comment]
I've kept duckduckgo as the DEFAULT search engine. Thats enough I think. Custom search strings should be the choice of the user imo.

**Comment by The-Compiler** [comment]
> What exactly are those :: links anyways, is that a standard URI form for external applications? Maybe we can parse/qualify it somehow differently to make searching for scoped C++ symbols work as expected?

[QUrl](http://doc.qt.io/qt-5/qurl.html) parses `foo::bar` as a valid URL with `foo` as scheme and `:bar` as path. I'm not sure if this is something sensible to do according to the URL standard. I guess `qutebrowser.urlutils.is_url` should handle this as a special case, and maybe a Qt bug should be submitted if this is invalid according to [RFC3986](https://tools.ietf.org/html/rfc3986) and the [WHATWG living URL standard](https://url.spec.whatwg.org/)? Do you want to look at this, @flvi0?

> I've kept duckduckgo as the DEFAULT search engine. Thats enough I think. Custom search strings should be the choice of the user imo.

I still think qutebrowser should offer some sensible defaults for configs, like e.g. for the ad block lists as well. As said, currently you should be able to remove entries by setting them to an empty URL (will look at why this is broken this evening), and with #499 I've to think about how to handle default values in general. But this is just a quick workaround for a debatable topic, so I'm closing this - sorry!

**Comment by flvi0** [comment]
Ok I've looked into this and it seems that double colon after scheme is allowed by the generic URI syntax.:

URI         = scheme ":" hier-part ...
hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
path-rootless = segment-nz *( "/" segment )
segment-nz    = 1*pchar
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

i.e. the colon is explicitly allowed there.

That being the case, I think we might still consider checking if there's actually some sort of handler registered for a given scheme. It seems QDesktopServices is missing some getUrlHandlers method to retreive a list of all handlers which are registered with the DE (where does that specifically happen actually?). We could then combine the list with any scheme handlers registered explicitly with qutebrowser (see #540) and search for a prefix in the URI. Everything else would then be treated as a search query with the default engine. 

That precludes of course the possibility to have users register scheme handlers dynamically if a yet unknown URI is entered. If that's planned, we might just stick with the slight annoyance of having to type the default search engine upfront if searching for a x::y string. Regarding #542, I still think that any named search engines should be a user setting, and if that case occurs well I have to give the default engine an explicit name.

**Comment by The-Compiler** [comment]
After talking with @flvi0 a bit I got conviced this actually might be a good idea indeed. I'll reopen and merge. Sorry for the hassle!

**Comment by The-Compiler** [comment]
After talking with @flvi0 a bit I got conviced this actually might be a good idea indeed. I'll reopen and merge. Sorry for the hassle!

**Comment by The-Compiler** [comment]
After talking with @flvi0 a bit I got conviced this actually might be a good idea indeed. I'll reopen and merge. Sorry for the hassle!

**Comment by The-Compiler** [comment]
After talking with @flvi0 a bit I got conviced this actually might be a good idea indeed. I'll reopen and merge. Sorry for the hassle!

**Comment by The-Compiler** [comment]
After talking with @flvi0 a bit I got conviced this actually might be a good idea indeed. I'll reopen and merge. Sorry for the hassle!

**Comment by error800** [comment]
yay, thanks! :)

**Pull request merged**
