### PR TITLE
Only split on ;; if not in quotes for commands

### PR DESCRIPTION
**Pull request by ryanjmortenson**
Pull request for issue #1850

### CODE REVIEW

**Comment by lahwaacz** [comment]
Your code prevents splitting of e.g. `"foo" ;; "bar"`. If we're going to introduce quoting rules to the command parsing, it should be done right.

**Comment by Kingdread** [comment]
Also, I don't think it correctly handles cases with escaped quotes (`\"`), and I'm not sure how this works with multiple quotations (something like `:message-info "foo" ;; message-info "bar"`), as the regex probably matches the whole `"foo" ;; message-info "bar"`.

I'm not sure if regex is the right tool for this, this could probably benefit from a "real" parser (together with the splitting).

**Comment by lahwaacz** [comment]
There is a "real" parser in [misc/split.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/misc/split.py) which should handle quotes properly. Then splitting on `;;` would mean just checking if the token is equal to `;;`. However, I think that the ShellLexer is not used for parsing commands at all, so switching to it would bring many new problems like stripping the quotes, which is not wanted for commands like `:open`.

**Comment by Kingdread** [comment]
The `ShellLexer` is able to keep the quotes, and it's used in `CommandRunner._split_args`. The problem is that the logic is a bit more complex (stuff like flags are always splitted), so I'm not sure how easy it'd be to use the lexer earlier in the process. It'd probably be necessary to run it more than once, depending on how the top-level string is splitted/parsed.

It'd probably be something like `lex without keeping anything -> split on ;; token -> lex commands separately again`

**Comment by lahwaacz** [comment]
With this two-pass approach, you'd have to strip the whitespace again, because `split("foo ;; bar", keep=True)` gives `['foo', ' ;;', ' bar']`. That's still not exactly right because e.g. `split("foo \;; bar", keep=True)` gives `['foo', ' \\;;', ' bar']`, so you don't have an easy way to detect the `;;` token after spliting with `keep=True`.

**Comment by Kingdread** [comment]
Do you mean the case where `;;` is not surrounded by whitespace? Like in

     :open /home/;;message-info "Home opened"

then yeah, that's a case I haven't thought about yet. The current behavior seems to be to still split it, so it would be good to keep that. We could however still see if the text is quoted, i.e. the difference between the command above and

     :open "/home/;;message-info Home opened"

Where the resulting split is `['open', ' "/home/;;message-info Test"']`, so we still can consider the `  "` prefix as "don't split this one". Or maybe we can teach the `ShellLexer` to treat `;;` as a special sequence and split there too (given it's not quoted).

But I agree that there is more to this than just "split early".

**Comment by lahwaacz** [comment]
Well, I was interested only in the backslash behaviour, but yeah - that's the generalization. The rest of my post is just nonsense, it was Python's doubling quotes that totally confused me.

**Comment by ryanjmortenson** [comment]
I guess I didn't grasp the scope of this problem before taking a stab at it.

**Comment by The-Compiler** [comment]
So should we close this? I agree the problem is probably more tricky than it seems first :wink:

**Comment by The-Compiler** [comment]
I'm closing this for now, as I unfortunately don't think it's a suitable solution. Thanks for the contribution though!

**Pull request closed without merging**
