### PR TITLE
Add a way to escape variables

### LINKED ISSUE #1861: Add a way to escape replacements in the commandline
In #1791 there was some discussion because there's no way to escape replacements like `{url}` in commands.

Moving this to here to make things easier, and so I don't forget that we should find a solution before v0.9.0.

cc @lahwaacz @blyxxyz

### PR DESCRIPTION
**Pull request by kobezda**
Variables such as {url} and {selection} can now be explicitly
escaped by double curly brackets: {{url}}, {{selection}}.

Only valid variables that would've been replaced are escaped,
so '{{notavariable}}' stays '{{notavariable}}'.

{{url} and {url}} both expand the variable.

This does *not* fully solve issue #1861

### CODE REVIEW

**Comment by lahwaacz** [comment]
This does not solve the original problem - pasting arbitrary input to `:open`. I'm definitely not going to replace every `{` with `{{` in the text I want to pass to the search engine. See https://github.com/The-Compiler/qutebrowser/pull/1791#issuecomment-239190008 for the first comment on the problem.

Regardless, your solution has a problem with the interpretation of e.g. `{{{url}}}`. Your regexes will split this as `{` + `{{url}}` + `}` so there will be no expansion of the `url` variable, but naturally it should be split as `{{` + `{url}` + `}}` and do the expansion. I think you'd need a _real_ parser for this.

**Comment by kobezda** [comment]
Good point, this doesn't fix issue 1861. 
Regarding the interpretation of `{{{url}}}` - yes, that's intentional, I've even explicitly noted so in tests.
Why do you think the second is more natural, and what should `{{{{url}}}}` do? `{{{` + `{url}` + `}}}`, or `{{` + `{{url}}` + `}}`?

**Comment by lahwaacz** [comment]
Because it's _natural_&trade; to define a formal grammar for the language and the second case would be [LL(1)](https://en.wikipedia.org/wiki/LL_grammar) language (you only need to look 1 character ahead), while the first case would be LL(*) (you need to consider only the last `{` in the sequence of opening curly brackets of arbitrary length). In the second case, `{{{{url}}}}` would be split as `{{` + `{{` + `url` + `}}` + `}}`. This is also the way [Python format language](https://docs.python.org/3/library/string.html#format-string-syntax) works.

**Comment by The-Compiler** [comment]
So should we close this for now?

**Comment by kobezda** [comment]
yes, let's close this.

**Pull request closed without merging**
