### PR TITLE
Add $QUTE_CONFIG_DIR for userscripts (#937)

### PR DESCRIPTION
**Pull request by blyxxyz**
A $QUTE_CONFIG_DIR variable with the location of the configuration dir, for #937.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! There are a few little issues with this:

- `standarddir.config()` can be `None` when started with `--configdir ""` - can you make sure to handle that?
- Can you add a test for the normal case and the `None` case (by using pytest's [monkeypatch](http://pytest.org/latest/monkeypatch.html), i.e. something like `monkeypatch.setattr('qutebrowser.utils.standarddir.config', lambda: None)`) to `tests/unit/commands/test_userscripts.py`? Let me know if you need help with that!
- Can you add this to the documentation in `doc/userscripts.asciidoc`?

**Comment by The-Compiler** [comment]
As mentioned in IRC, there's no test for the `userscripts.run` function yet, where that environment variable gets set. I'd like to add one before merging.

**Comment by The-Compiler** [comment]
I'll postpone that test to later™, as QtWebEngine-work is currently more important :wink:

Could you maybe add a `$QUTE_DATA_DIR` as well? There are userscripts which use that kind of thing already.

If you know bash well enough, can you please also adjust existing userscripts in `misc/userscripts` to use that instead of the homegrown solutions they use currently?

**Comment by The-Compiler** [comment]
Is this ready to review again? AppVeyor segfaulted again, not sure what's triggering this...

**Comment by blyxxyz** [comment]
Yes.

**Comment by The-Compiler** [comment]
LGTM - @t-wissmann @Zach-Button @halfwit if you have a minute, can you maybe take a quick look at the shellscript changes? A second pair of eyes can't hurt :wink:

**Pull request merged**
