### PR TITLE
Only load with :edit-url if the URL was changed, remove count argument

### PR DESCRIPTION
**Pull request by blyxxyz**
See #1604.

### CODE REVIEW

**Comment by The-Compiler** [comment]
LGTM, thanks! Waiting for the checks to finish...

**Comment by blyxxyz** [comment]
```19:07:38 ERROR    message    message:error:308 Error while splitting command: No closing quotation```
Is this a problem with the tests or with my code?

**Comment by The-Compiler** [comment]
That's an expected error in the log output - I just opened #1611 to make this more clear in the future.

However, I see two issues in that log:

- `test_editing_an_url_with_count` fails
- There is a segfault in `test_running_spawn_with_invalid_quoting` I've never seen before - feel free to ignore that one

Also not sure why Travis isn't picking this PR up?

**Comment by The-Compiler** [comment]
Looking better now - will merge this after getting some sleep :wink:

**Comment by The-Compiler** [comment]
Thanks! This didn't actually work for me as vim added a trailing newline to the URL, but I added a `.rstrip('\n')` to fix that.

**Comment by blyxxyz** [comment]
I had that too (with Emacs), but I didn't think it was a problem. This addresses situations where you immediately exit the editor, and the newline is added when saving, not when exiting. Does vim handle it differently?

It doesn't hurt, of course.

**Comment by The-Compiler** [comment]
Ah, right, I probably tested with `:wq` and not `:q!` - but yeah, makes sense to strip it off either way.

**Comment by blyxxyz** [comment]
Does it work properly on Windows, with its `\r\n` newlines?

**Comment by The-Compiler** [comment]
I didn't try and didn't find an easy way to write a test for this - but I'd expect it to work as Python normalizes newlines with `open()` by default.

**Pull request merged**
