### PR TITLE
Update list of user-agent completions

### LINKED ISSUE #923: Update browser list for UA completion
The browser list in the completion for `network -> user-agent` is a bit dated - it should probably be updated to show more recent versions.

Ideally there'd be some script to grab this from some list of most common user agents or so, so I can easily update it with every release.

### PR DESCRIPTION
**Pull request by lamarpavel**
This is meant to fix #923, though I'm not sure how much diversity of available agents is wanted beyond the list of most popular ones.

Also, I hope it's okay to use the script @averrin posted in #923

### CODE REVIEW

**Comment by lamarpavel** [comment]
Tests are failing because the new script imports `requests` and `lxml`. I wasn't sure about including the script in the repo as it's just a helper and has nothing to do with the code of qutebrowser. One solution might be to include it but have tox ignore it.

**Comment by The-Compiler** [comment]
Please add `requests==2.8.1` to `[testenv:pylint]` in `tox.ini` - then that'll be checked too. For lxml, there's some trouble with installing it on Windows, so I think you can simply add `# pylint: disable=import-error` on the import line.

I think it's good to include the script, I have various helper scripts in the repo - however it should go to `scripts/dev`.

Can you also add the GPL boilerplate to the file please? Something like this:

```
# Copyright 2015 lamarpavel
# Copyright 2015 Alexey Nabrodov ("Averrin")
#
# This file is part of qutebrowser.
#
# qutebrowser is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# qutebrowser is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with qutebrowser.  If not, see <http://www.gnu.org/licenses/>.
```

As for the diversity: As you mention, we might want to add some user agents by hand. I'm not sure if the Google Bot/wget/curl entries are really needed, but I think Mobile Safari/Firefox will be useful.

**Comment by averrin** [comment]
Nice to be useful :smile:

**Comment by lamarpavel** [comment]
Alright, done what you suggested, @The-Compiler, let's see if the tests complete this time.

I'm also working on another minor improvement in the script regarding line breaks; as of right now you manually have to split the strings printed by the script or pylint will yell at you for stepping over the 80th column.

**Comment by The-Compiler** [comment]
The [textwrap](https://docs.python.org/3.5/library/textwrap.html) module might be useful.

**Comment by lamarpavel** [comment]
So, I basically re-wrote the script to add some functionality. First of all, it can now be configured to include several different versions of every browser rather than just the most popular ones; it is currently set up to find the top entries for firefox, safari and chrome, each on a few different OSs.
Additionally, it outputs the entries grouped by browser name with a newline inbetween.

It does not do the line breaking, but since it will only be invoked once every few months it should be okay to do that manually.

**Comment by The-Compiler** [comment]
I don't get how `filter_list` works exactly, but I'm tired and it seems to do the right thing, so I'll merge :wink:

**Comment by lamarpavel** [comment]
`filter_list` is probably not doing the most elegant thing to solve the problem, but this was my first forray into python datastructures and since it's just a misc script and not a part of qutebrowser that users have to rely on... I was kinda adventerous.

**Pull request merged**
