### PR TITLE
Fix importer script to output bookmarks in the right format for qutebrowser to use

### PR DESCRIPTION
**Pull request by craftyguy**
This prints each bookmark it reads from html in the format "url title". Previously, if you tried to select a bookmark, qutebrowser would search for the bookmark's title using your search engine of choice rather than visit the url.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Hmm, weird - I'm quite sure that worked in the past?! cc @claudehohl

**Comment by phansch** [comment]
Hm, I suppose everyone has been importing bookmarks into the quickmarks file until now, which has the format the other way around.

**Comment by craftyguy** [comment]
Hmm, so this script is for importing into bookmarks or quickmarks? Maybe the solution is to change the name of the script to something like "quickmark-importer", or modify the script to handle both based on a new parameter?

**Comment by The-Compiler** [comment]
Oh, indeed! When @claudehohl originally wrote it, only quickmarks existed, so it made sense to call it bookmark importer (as it imports bookmarks, after all).

I think adding a parameter would be the best solution, until at some point in the future when bookmarks/quickmarks are getting merged anyways. (#882)

**Comment by craftyguy** [comment]
Ok I'll add a parameter (-b for "bookmarks" or something). I'm thinking that the parameter should be optional and the default behavior is the current behavior (output quickmark format) so that existing scripts that folks might have are not impacted by this change. What do you think?

**Comment by The-Compiler** [comment]
:+1:

**Comment by craftyguy** [comment]
Ok, this commit adds a new option to the script, -b, that will cause it to output in a format that qutebrowser expects for bookmarks. Default option (no -b) is to output in the quickmark format.

I also tweaked the 'help' section a little to make it a little more clear as to what the user is expected to put in for the 'browser' and 'bookmarks' options since it was a little vague :)

**Pull request merged**
