### PR TITLE
Add new completion -> auto-open option.

### PR DESCRIPTION
**Pull request by The-Compiler**
An (IMHO) cleaner version of #705.

@Carpetsmoker could you maybe test (and if you want code-review) this, and tell me if it does what you want it to?

Docstrings are still missing as I need to start work now :wink:

### CODE REVIEW

**Comment by Carpetsmoker** [comment]
If I type `:se<Tab>` I get the completion menu with a number of options, and `:search` filled in (as expected), but pressing `<Tab>` again makes the completion menu disappear.

**Comment by The-Compiler** [comment]
Whoops - should be fixed now! Can you please try again?

**Comment by The-Compiler** [comment]
I merged this now as it looks good to me - if you notice anything being off, please let me know!

**Comment by Carpetsmoker** [comment]
I discovered another issue:

- `:s<Tab>`, will complete to `:save`.
- Backspace until you end up with just `:s`
- Type `e`, it will now be completed to `:search` (which is not what I would expect).

**Comment by The-Compiler** [comment]
That seems to be the same as #748 (and not connected to the `auto-open` option, i.e. it also happens with `auto-open = true`) :smile:

**Comment by Carpetsmoker** [comment]
Hm, I thought this didn't happen with older versions, but perhaps I'm mistaken.

**Comment by The-Compiler** [comment]
I just verified it happens with v0.1 as well, so I'm pretty sure it's the linked bug.

**Pull request merged**
