### PR TITLE
Fix for "Help not discoverable" (#1490)

### PR DESCRIPTION
**Pull request by engelju**
For #1490: I've added the http://qutebrowser.org/doc/help/ page to the main menu. Please tell me what you think.

### CODE REVIEW

**Comment by The-Compiler** [comment]
The Travis failure is unrelated to your change, I messed something up in master... :fearful: 

Adding it to the menu sounds like a good and straightforward solution, thanks!

**Comment by The-Compiler** [comment]
Oh... Since it's in `/doc/help/` the relative links break again (linking to e.g. `doc/FAQ.html`). Not sure what the best way would be to fix this and not break it somewhere else - do you want to take a look? :wink:

**Comment by engelju** [comment]
Ow, yeah I see it now. 😅  Sure, I'll have a look!

**Comment by engelju** [comment]
> Quick organisation question: [...], or can I keep working on this branch and just keep pushing?

Somehow I wasn't able to do that. 😕  I stayed on ```engelju:1490-help-not-discoverable```, rebased master onto it, edited the respective file and pushed, but on Github it forced me to create a new PR... So there's #2056 now.

**Comment by The-Compiler** [comment]
You can keep pushing to open PRs, but I don't think pushing to a branch with a closed PR will work - so a new PR is fine!

**Pull request merged**
