### PR TITLE
[WIP] Greasemonkey support

### PR DESCRIPTION
**Pull request by andor44**
**This PR is a work in progress**. With that noted, it is quite usable already. Scripts without external dependencies work well for the most part.

### CODE REVIEW

**Comment by andor44** [comment]
An incomplete list of things to be done for this to be considered complete:

- [x] Basic JS userscript execution support
- [x] Support all "standard" `GM_` functions
- [x] Execution at the correct time (document start/end)
- [ ] External dependency loading
- [ ] General code cleanup
    - [ ] Comments, docs, license
    - [ ] Properties
- [ ] User commands
    - [ ] Install (download?)
    - [ ] Remove
- [ ] More graceful (?) error handling

Desirable things, outside of the scope of my work in this PR:
- Sandboxing protected `GM_` functions
- (Automatic) update of userscripts


I'm also open to suggestions for other improvements.

**Comment by The-Compiler** [comment]
Some other things which come to mind from a quick look:

- Move the javascript template to its own file, e.g. `qutebrowser/javascript/greasemonkey.js`.
- Use [jinja](http://jinja.pocoo.org/) for the javascript template - this means:
    - Add something like `js_env = jinja2.Environment(loader=Loader('javascript'))` to `qutebrowser/utils/jinja.py`
    - Do `from qutebrowser.utils import jinja` and use `jinja.js_env.get_template('greasemonkey.js').render(script_id=...)` or so.
    - Now you can use `{` and `}` literally and use `{{ script_id }}`.
- Use Python's [os.path](https://docs.python.org/3/library/os.path.html) instead of Qt's `QDir`/`QFile`.

**Comment by The-Compiler** [comment]
FYI, closing/reopening to get Travis CI to look at it.

**Comment by andor44** [comment]
I use `QDir` and `QFile` because they make the enumeration/listing of the directory trivial. I could do it manually with `os.path` but I'm more comfortable relying os Qt doing the right thing there. I'll make the other changes you suggested, and make the tests pass, and then this PR should be ready for a re-evaluation.

**Comment by The-Compiler** [comment]
You can just use Python's [glob](https://docs.python.org/3/library/glob.html) module instead, i.e. something like:

```python
for script_filename in glob.glob(os.path.join(scripts_dir, '*.js')):
    if not os.path.isfile(script_filename):
         continue
```

I agree it's a bit verbose, but I prefer that to using a completely different API just for that.

**Comment by bb010g** [comment]
bumpity bump

**Comment by The-Compiler** [comment]
Closing this for now as it seems to be dead - @andor44, if you feel like working on this again, feel free to reopen or open a new PR! Also, please keep the repo/branch around, as the PR is linked from the issue and might be useful when looking at this again in the future.

This will probably be easier to implement with QtWebEngine (#666) too, as that has an API for greasemonkey-like scripts.

Thanks for your contribution either way!

**Pull request closed without merging**
