### PR TITLE
[wip] unit tests for browser/history.py

### PR DESCRIPTION
**Pull request by neeasade**
ref: #999 

[wip]

### CODE REVIEW

**Comment by The-Compiler** [comment]
@neeasade any update on this? :smile:

**Comment by neeasade** [comment]
ah, I'd kinda forgotten about this a little. will return to it this evening if not one else has expressed want to test this.

**Comment by neeasade** [comment]
closing this, other priorities currently, sorry.

**Comment by The-Compiler** [comment]
No worries, and thanks for letting me know!

I added a note to #999, so I'd like to ask you to keep the branch/repo alive at the moment if that's okay.

**Comment by neeasade** [comment]
Yepp will do :)

**Pull request closed without merging**
