### PR TITLE
qute://settings: set valid type of <input> fields

### LINKED ISSUE #1883: Focusing input fields in qute://settings does not enter insert mode
If you go to qute::settings then focus an option, qb doesn't enter insert mode.

```
qutebrowser v0.8.1
Git commit: v0.8.0-813-gbcb06f0 (2016-08-19 15:47:35 +0200)

CPython: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g-fips  1 Mar 2016

Platform: Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Desktop: i3
Frozen: False
Imported from /home/teto/qutebrowser/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

```

### PR DESCRIPTION
**Pull request by lahwaacz**
fixes #1883

### CODE REVIEW

**Comment by The-Compiler** [comment]
FWIW I planned to write a simple end2end test for changing a setting via `qute:settings` (and one with an invalid value) which would have cought this bug before merging the PR - but so far I didn't get to it yet.

If you have the time and feel like it, want to add one yourself? :wink:

**Comment by lahwaacz** [comment]
Would it be fine to test if `:hints inputs` doesn't show `No elements found` error? Clicking the hints might actually be a bad idea due to #70 (first point).

**Comment by The-Compiler** [comment]
I don't think that's still an issue, since nowadays we just [move](https://github.com/The-Compiler/qutebrowser/blob/388d771a2e79094c45618ab846c5d0268fe3cf92/qutebrowser/browser/webelem.py#L393-L394) the caret to the end after clicking.

**Comment by lahwaacz** [comment]
Oh, I haven't noticed until now :+1:

**Comment by lahwaacz** [comment]
I can't make changing settings via `qute://settings` from tests to work. I tried

```gherkin
    Scenario: Focusing input fields in qute://settings and entering valid value
        When I open qute://settings
        And I hint with args "inputs" and follow a
        And I press the key "<Ctrl+Backspace>"
        And I press the key "true"
        And I press the key "<Escape>"
        And I run :set general ignore-case?
        Then "general ignore-case = true" should be logged
```

and even though the input field seems to be changed correctly (confirmed by running with `--no-xvfb`), the setting is never actually changed.

**Comment by The-Compiler** [comment]
Does it work if you add a `<Tab>` press to explicitly unfocus the field?

**Comment by lahwaacz** [comment]
Hmm, for some reason it does - though I don't know why, in normal browser it seems to be set immediately after I leave the insert mode.

And also the extra `Tab` does not help with the invalid value test:

```gherkin
    Scenario: Focusing input fields in qute://settings and entering invalid value
        When I open qute://settings
        And I hint with args "inputs" and follow a
        And I press the key "<Ctrl+Backspace>"
        And I press the key "foo"
        And I press the key "<Escape>"
        Then "invalid value 'foo' *" should be logged
```

**Comment by The-Compiler** [comment]
I'd say `set.feature` - it seems the tests don't find the input fields though?

**Comment by lahwaacz** [comment]
Heh, how wide is the screen on Travis and on my laptop with xvfb? The table in `qute://settings` is pretty wide and doesn't shrink if the window is too small, so maybe we'll need to scroll to the right edge.

**Comment by The-Compiler** [comment]
Oh, good point! It's 800x600 by default.

**Comment by lahwaacz** [comment]
If the width is the same on Travis and my computer (which should be in xvfb), then it must be my font configuration making the table narrower to fit in the screen. Though 800px sounds pretty wide...

**Comment by lahwaacz** [comment]
So now only the test for setting an invalid value fails...

**Comment by The-Compiler** [comment]
You didn't actually tab away from the field there though.

**Comment by lahwaacz** [comment]
Well, at first I tested on localhost that it shouldn't have helped there, but apparently that was only due to the [capitalization problem](https://github.com/The-Compiler/qutebrowser/pull/1884/commits/b272fce2cf5dee368ad92abed8a5b225debcc0f9) in the catched message...

**Comment by The-Compiler** [comment]
Thanks! I did a few improvements to the tests in 1c0cbc326936478579eb23452efa8266e9e0c529.

**Pull request merged**
