### PR TITLE
Add :window-only command

### PR DESCRIPTION
**Pull request by haasn**
Inspired by an IRC conversation about the overuse of "Given I have a fresh instance", I implemented this command to greatly cut down on the need for it, and did a quick pass through all of those usages to slim them down.

### CODE REVIEW

**Comment by haasn** [comment]
Incidentally, we could remove two more usages in `urlmarks.feature` either by ordering those to the beginning (easy) or by adding `:clear-bookmarks`, `:clear-quickmarks` commands (probably best to hide them by default if so).

Not sure if it's worth it for just one test (respectively), though.

**Comment by The-Compiler** [comment]
I haven't taken a closer look yet, but do you have an idea what could cause all the [test failures](https://travis-ci.org/The-Compiler/qutebrowser/jobs/151659025) on Travis?

```
Traceback (most recent call last):
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/config/config.py", line 120, in wrapper
    return func(wrapper_self)
  File "/home/travis/build/The-Compiler/qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 69, in init_config
    tabbar = self.tabBar()
AttributeError: 'NoneType' object has no attribute 'tabBar'
```

**Comment by haasn** [comment]
No, I haven't taken a closer look at it either. I was probably just slightly overzealous in removing some “fresh instance” checks, although I did go through them all and make sure it actually made sense to remove them.

**Comment by The-Compiler** [comment]
Gaaah... This seems to be yet another instance where on Ubuntu Trusty, with PyQt 5.2, signals of already dead objects don't get disconnected properly... Yet another reason for #1775.

I'll try to fix this in master and re-run the tests.

**Comment by The-Compiler** [comment]
ccce55443f3a391108129c6ffb5472c085bc58b0 fixed it, and from a (very quick) unscientific look it seems to speed up the testsuite by some 30 seconds! :tada:

**Comment by The-Compiler** [comment]
Thanks! I moved the command to `qutebrowser.misc.utilcmds` in 882d1a5e8873fe453e087681dc053df14110e66b as it doesn't actually need any of the utility methods of `CommandDispatcher` (and I'd like to completely get rid of `qutebrowser.browser.commands` one day).

**Pull request merged**
