### PR TITLE
Fixed issue #1896.

### PR DESCRIPTION
**Pull request by antoyo**
This fixes issue #1896.

### CODE REVIEW

**Comment by The-Compiler** [comment]
`createWindow` is not only called via javascript, so this [breaks](https://travis-ci.org/The-Compiler/qutebrowser/jobs/155517055) various things.

I haven't looked at #1896 yet, but this should fully be handled by QtWebKit by setting the setting (which we do).

**Comment by antoyo** [comment]
You are right: the `target="_blank"` links do not work with this fix (but they should).
However, the `QWebSettings.JavascriptCanOpenWindows` does not work: setting it to `False` still make qutebrowser calls `createWindow` on `window.open`.

**Comment by The-Compiler** [comment]
By the way: I hoped me outright closing this didn't seem rude - I was a bit short on time, and that certainly wasn't intended :wink:

If you find a way to make this work without breaking other places where `createWindow` is called I'm all ears - unfortunately I'm not aware of one. I want to check #1896 with QtWebEngine once `createWindow` is implemented there, and if it works there, that's probably all we can do...

**Comment by antoyo** [comment]
No problem :) .

**Pull request closed without merging**
