### PR TITLE
Focus field before filling password

### PR DESCRIPTION
**Pull request by paretje**
On some websites, e.g. https://www.engie-electrabel.be, you can't login after you filled the login form using `password_fill`. This can be fixed by focusing the input fields, and removing focus afterwards.

### CODE REVIEW

**Comment by The-Compiler** [comment]
LGTM, but pinging @t-wissmann for that one too :wink:

**Comment by t-wissmann** [comment]
Looking only quickly, I couldn't find the login form on the above mentioned website.
After applying your changes, everything still works for me, so no objections from my side :-)

**Comment by The-Compiler** [comment]
I'm guessing it's e.g. on https://www.engie-electrabel.be/fr/independants/start

Will merge this tomorrow morning :wink:

**Comment by t-wissmann** [comment]
Strangely, that form works for me without the `input.focus()` and `input.blur()` lines. So either it's a different form, or something is wrong with @paretje's setup.

**Comment by The-Compiler** [comment]
Whatever, can't hurt! Thanks @paretje and thanks @t-wissmann for the help!

**Comment by paretje** [comment]
Strange, when I try that page, the button is not clickable without this PR. What about the form on [this page](https://www.engie-electrabel.be/nl/particulier/) after clicking on "Energiedesk"? The button stays kind of transparent without clicking the fields.

**Comment by t-wissmann** [comment]
Indeed! At that page the login button is disabled without clicking into some of the form fields first.

**Pull request merged**
